apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydeployment-nginx
  template:
    metadata:
      labels:
        app: mydeployment-nginx
    spec:
      containers:
      - name: mydeployment-nginx
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
